# Generated by Django 5.0.3 on 2024-03-22 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='author',
        ),
        migrations.AddField(
            model_name='drink',
            name='author_id',
            field=models.ForeignKey( default=None , on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
