# Generated by Django 5.0.3 on 2024-03-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_drink_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='author_id',
            new_name='author',
        ),
    ]
